pipeline {
    agent {
        docker {
            image 'node:20.11.0-alpine3.19'
            args '--user root:root --publish 3000:3000 --publish 5000:5000 --name docker-from-jenkins'
            reuseNode true
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') { 
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        
        // #########################################
        stage('Build image') {
            when {
                branch 'development' 
            }
            steps {
                echo 'Starting to build docker image'
                
                // Questo funziona correttamente
                sh 'apk update && apk add docker-cli'
                sh 'docker -v'
                //sh 'docker image rm test-image:1'
                sh 'docker build --force-rm=true -t test-image:${BUILD_ID} -f Dockerfile .'
                
                //script {
                //    def customImage = docker.build("test-image:1")
                //    //def customImage = docker.build("my-image:${env.BUILD_ID}")
                //    //customImage.push()
                //}
            }
        }
        // #########################################

        stage('Deliver for development') {
            when {
                branch 'development' 
            }
            steps {
                sh './jenkins/scripts/deliver-for-development.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }

        stage('Deploy for production') {
            when {
                branch 'production'  
            }
            steps {
                sh './jenkins/scripts/deploy-for-production.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
